### ISSUE TITLE
Error caused by CORS policy

### ISSUE THREAD

**Issue by SimonDuperray** [Elegye/Renault-AutoRadio-Code#1]
## Issue

I'm using Brave browser on a Windows 10 machine and I get the following errors when I try to input U522 in the form:

```
- Access to fetch at 'file:///D:/dl/Renault-AutoRadio-Code/codes.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.
- GET file:///D:/dl/Renault-AutoRadio-Code/codes.json net::ERR_FAILED
- Uncaught (in promise) TypeError: Failed to fetch
```

I tried to use asynchronous function instead of the fetch one but it did not change anything.

**Comment by Elegye** [comment]
I suppose you have cloned the repository and just open the index.html file.

If so, you should always use development server to be sure you are not running the app on your local file system.
